from deephive.environment.reward_schemes.full_reward import FullRewardScheme
from deephive.environment.reward_schemes.sparse_reward import SparseRewardScheme
from deephive.environment.reward_schemes.custom_reward import CustomRewardScheme
from deephive.environment.reward_schemes.explorers_reward import ExplorersRewardScheme