from deephive.environment.observation_schemes.default_scheme import DefaultObservationScheme
from deephive.environment.observation_schemes.explorers_scheme import ExplorersObservationScheme
from deephive.environment.observation_schemes.simple_scheme import SimpleObservationScheme